"""add hash processing status

Revision ID: 741e1140aad4
Revises: 7b42bc4bfcc8
Create Date: 2026-10-05 19:59:32.748523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741e1140aad4'
down_revision: Union[str, Sequence[str], None] = '7b42bc4bfcc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('hash_status', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_files_hash_status'), 'files', ['hash_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_hash_status'), table_name='files')
    op.drop_column('files', 'hash_status')
    # ### end Alembic commands ###
